/**
* Systems Modeling API and Services
* REST/HTTP platform specific model (PSM) for the Systems Modeling API and Services
*
* The version of the OpenAPI document: 1.0
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openmbee.flexo.sysmlv2.apis

import io.ktor.server.application.*
import io.ktor.server.response.*
import io.ktor.server.resources.get
import io.ktor.server.resources.delete
import io.ktor.server.routing.*
import kotlinx.serialization.json.Json

import org.apache.jena.rdf.model.Property
import org.apache.jena.rdf.model.RDFNode
import org.apache.jena.rdf.model.ResourceFactory
import org.apache.jena.vocabulary.DCTerms
import org.apache.jena.vocabulary.RDF
import io.ktor.http.*
import org.openmbee.flexo.sysmlv2.*
import org.openmbee.flexo.sysmlv2.infrastructure.generateId
import org.openmbee.flexo.sysmlv2.infrastructure.requireValidId
import org.openmbee.flexo.sysmlv2.models.Branch
import org.openmbee.flexo.sysmlv2.models.BranchRequest
import org.openmbee.flexo.sysmlv2.models.Identified
import java.time.OffsetDateTime

fun FlexoModelHandler.branchFromResponse(
    outgoing: Map<Property, Set<RDFNode>>,
    projectId: String,
    branchId: String
): Branch? {
    val commitSuffix = outgoing[MMS.commit]?.resource()?.uri?.uriSuffix ?: return null
    val commit = Identified(commitSuffix)
    // never fabricate created/name for malformed upstream data — invented
    // values mask triplestore bugs (see issue #20)
    return Branch(
        atId = branchId,
        atType = Branch.AtType.Branch,
        created = OffsetDateTime.parse(outgoing[MMS.created]?.literal() ?: return null),
        owningProject = Identified(projectId),
        referencedCommit = commit,
        name = outgoing[DCTerms.title]?.literal() ?: return null,
        head = commit
    )
}
fun Route.BranchApi() {

    delete<Paths.deleteBranchByProjectAndId> { path ->
        requireValidId(path.projectId, "projectId")
        requireValidId(path.branchId, "branchId")
        // add annotation to indicate it's deleted
        val patchResponse = flexoRequestPatch {
            orgPath("/repos/${path.projectId}/branches/${path.branchId}")
            sparqlUpdate {
                """
                    insert data {
                        <> <${SYSMLV2.DELETED.uri}> true .
                    }
                """.trimIndent()
            }
        }
        if (patchResponse.isFailure()) {
            return@delete forward(patchResponse)
        }
        val branch = patchResponse.parseModel {
            model.listSubjectsWithProperty(RDF.type, MMS.Branch).mapWith {
                branchFromResponse(it.outgoing(), path.projectId, it.uri.uriSuffix)
            }.toList().filterNotNull().firstOrNull()
        } ?: return@delete call.respond(HttpStatusCode.NotFound)
        call.respond(branch)
    }

    get<Paths.getBranchesByProject> { path ->
        requireValidId(path.projectId, "projectId")
        // submit GET request for all branches
        val flexoResponse = flexoRequestGet {
            orgPath("/repos/${path.projectId}/branches")
        }
        // forward failures to client
        if(flexoResponse.isFailure()) {
            return@get forward(flexoResponse)
        }
        // parse the response model, convert it to JSON, and reply to client
        call.respond(flexoResponse.parseModel {
            model.listSubjectsWithProperty(RDF.type, MMS.Branch).filterDrop {
                (it.hasProperty(SYSMLV2.DELETED) || it.uri.uriSuffix == "master")
            }.mapWith {
                branchFromResponse(it.outgoing(), path.projectId, it.uri.uriSuffix)
            }.toList().filterNotNull()
        })
    }

    get<Paths.getBranchByProjectAndId> { path ->
        requireValidId(path.projectId, "projectId")
        requireValidId(path.branchId, "branchId")
        val flexoResponse = flexoRequestGet {
            orgPath("/repos/${path.projectId}/branches/${path.branchId}")
        }
        // forward failures to client
        if(flexoResponse.isFailure()) {
            return@get forward(flexoResponse)
        }
        // parse the response model, convert it to JSON, and reply to client
        val branch = flexoResponse.parseModel {
            // soft-deleted branches are invisible
            model.listSubjectsWithProperty(RDF.type, MMS.Branch).filterDrop {
                it.hasProperty(SYSMLV2.DELETED)
            }.mapWith {
                branchFromResponse(it.outgoing(), path.projectId, it.uri.uriSuffix)
            }.toList().filterNotNull().firstOrNull()
        } ?: return@get call.respond(HttpStatusCode.NotFound)
        call.respond(branch)
    }

    post<BranchRequest>("/projects/{projectId}/branches") { request ->
        val projectId = call.parameters["projectId"]!!
        requireValidId(projectId, "projectId")
        request.atId?.let { requireValidId(it, "@id") }
        requireValidId(request.head.atId, "head.@id")
        // use provided branch ID or generate one if not provided
        val branchId = request.atId ?: generateId()
        val createBranchResponse = flexoRequestPost {
            orgPath("/repos/${projectId}/branches")
            // set branch ID slug
            addHeaders(
                "Slug" to branchId
            )
            turtle {
                thisSubject(
                    MMS.ref to ResourceFactory.createResource("../locks/Commit.${request.head.atId}"),
                    DCTerms.title to request.name.en
                )
            }
        }
        // forward failures to client
        if(createBranchResponse.isFailure()) {
            return@post forward(createBranchResponse)
        }
        call.respond(createBranchResponse.parseLdp {
            branchFromResponse(focalOutgoing, projectId, branchId)
                ?: throw IllegalStateException("Layer1 did not return mms:commit for newly created branch $branchId")
        })
    }
}
