/**
* Systems Modeling API and Services
* REST/HTTP platform specific model (PSM) for the Systems Modeling API and Services
*
* The version of the OpenAPI document: 1.0
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openmbee.flexo.sysmlv2.apis

import io.ktor.server.application.*
import io.ktor.server.response.*
import io.ktor.server.resources.get
import io.ktor.server.resources.delete
import io.ktor.server.routing.*
import kotlinx.serialization.json.Json
import kotlinx.serialization.decodeFromString
import org.apache.jena.rdf.model.Property
import org.apache.jena.rdf.model.RDFNode
import org.apache.jena.rdf.model.ResourceFactory
import org.apache.jena.vocabulary.DCTerms
import org.apache.jena.vocabulary.RDF
import org.openmbee.flexo.sysmlv2.*
import org.openmbee.flexo.sysmlv2.models.Branch
import org.openmbee.flexo.sysmlv2.models.BranchRequest
import org.openmbee.flexo.sysmlv2.models.Identified
import java.time.OffsetDateTime
import java.util.*

fun FlexoModelHandler.branchFromResponse(
    outgoing: Map<Property, Set<RDFNode>>,
    projectUuid: UUID,
    branchUuid: UUID
): Branch {
    val commit = Identified(UUID.fromString(outgoing[MMS.commit]!!.resource()!!.uri.uriSuffix))
    return Branch(
        atId = branchUuid,
        atType = Branch.AtType.Branch,
        created = OffsetDateTime.parse(
            outgoing[MMS.created]?.literal()
                ?: OffsetDateTime.now().toString()
        ),
        owningProject = Identified(projectUuid),
        referencedCommit = commit,
        name = outgoing [DCTerms.title]?.literal() ?: "",
        head = commit
    )
}
fun Route.BranchApi() {

    delete<Paths.deleteBranchByProjectAndId> {
        val exampleContentString = """{
          "head" : {
            "@id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91"
          },
          "@type" : "Branch",
          "created" : "2000-01-23T04:56:07.000+00:00",
          "name" : "name",
          "@id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
          "referencedCommit" : {
            "@id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91"
          },
          "owningProject" : {
            "@id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91"
          }
        }"""
        call.respond(Json.decodeFromString<Branch>(exampleContentString))
    }

    get<Paths.getBranchesByProject> { path ->
        // submit GET request for all branches
        val flexoResponse = flexoRequestGet {
            orgPath("/repos/${path.projectId}/branches")
        }
        // forward failures to client
        if(flexoResponse.isFailure()) {
            return@get forward(flexoResponse)
        }
        // parse the response model, convert it to JSON, and reply to client
        call.respond(flexoResponse.parseModel {
            val branches = mutableListOf<Branch>()
            model.listSubjectsWithProperty(RDF.type, MMS.Branch).forEach {
                if (it.uri.uriSuffix == "master") {
                    return@forEach
                }
                branches.add(branchFromResponse(it.outgoing(), path.projectId, UUID.fromString(it.uri.uriSuffix)))
            }
            branches
        })
    }

    get<Paths.getBranchesByProjectAndId> { path ->
        val flexoResponse = flexoRequestGet {
            orgPath("/repos/${path.projectId}/branches/${path.branchId}")
        }
        // forward failures to client
        if(flexoResponse.isFailure()) {
            return@get forward(flexoResponse)
        }
        // parse the response model, convert it to JSON, and reply to client
        call.respond(flexoResponse.parseModel {
            model.listSubjectsWithProperty(RDF.type, MMS.Branch).mapWith {
                branchFromResponse(it.outgoing(), path.projectId, UUID.fromString(it.uri.uriSuffix))
            }.toList()[0]
        })
    }

    post<BranchRequest>("/projects/{projectId}/branches") { request ->
        val projectId = call.parameters["projectId"]
        val branchId = UUID.randomUUID()
        val createBranchResponse = flexoRequestPost {
            orgPath("/repos/${projectId}/branches")
            // set branch ID slug
            addHeaders(
                "Slug" to branchId.toString()
            )
            turtle {
                thisSubject(
                    MMS.ref to ResourceFactory.createResource("../locks/Commit.${request.head.atId}"),
                    DCTerms.title to request.name.en
                )
            }
        }
        // forward failures to client
        if(createBranchResponse.isFailure()) {
            return@post forward(createBranchResponse)
        }
        call.respond(createBranchResponse.parseLdp {
            branchFromResponse(focalOutgoing, UUID.fromString(projectId), branchId)
        })
    }
}
