/**
* Systems Modeling API and Services
* REST/HTTP platform specific model (PSM) for the Systems Modeling API and Services
*
* The version of the OpenAPI document: 1.0
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openmbee.flexo.sysmlv2.apis

import io.ktor.http.*
import io.ktor.server.application.*
import io.ktor.server.resources.*
import io.ktor.server.response.*
import io.ktor.server.routing.*
import kotlinx.serialization.json.*
import org.apache.jena.rdf.model.Property
import org.apache.jena.rdf.model.RDFNode
import org.apache.jena.vocabulary.RDF
import org.apache.jena.vocabulary.XSD
import org.openmbee.flexo.sysmlv2.*
import org.openmbee.flexo.sysmlv2.infrastructure.requireValidId

fun modelElementConstructQuery(elementTarget: String="?__element"): String {
    return """
        construct {
            $elementTarget a ?element_type ; 
                ?element_p ?element_o .
        }
        where {
            $elementTarget a ?element_type ;
                ?element_p ?element_o .
        }
    """.trimIndent()
}

fun listElementsConstructQuery(limit: Int?=null, offset: Int?=null): String {
    if (limit == null && offset == null) return """
        construct {
            ?s ?p ?o .
        } where {
            ?s ?p ?o .
        }
    """.trimIndent()
    return """
        prefix sysml: <https://www.omg.org/spec/SysML#>
        construct {
            ?e ?element_p ?element_o .
        }
        where {
            {
                 select ?e
                 where {
                     ?e sysml:elementId ?id .
                 } order by ?id limit $limit offset $offset
            }
            ?e ?element_p ?element_o .
        }
    """.trimIndent()
}

class InvalidTripleError(
    message: String,
    subjectIri: String,
    predicate: Property,
    value: RDFNode
): Error("$message at <$subjectIri> <${predicate.uri}> ${value.stringify()}")

private fun FlexoModelHandler.jsonFromRdfNode(elementIri: String, predicate: Property, obj: RDFNode): JsonElement {
    return if (obj == RDF.nil) {
        JsonNull
    } else if (obj.isResource) {
        buildJsonObject {
            put("@id", obj.asResource().uri.autoSuffix)
        }
    } else if (obj.isLiteral) {
        val lit = obj.asLiteral()

        // depending on its datatype
        when (lit.datatype.uri) {
            XSD.xboolean.uri -> JsonPrimitive(lit.boolean)
            XSD.integer.uri -> JsonPrimitive(lit.int)
            XSD.decimal.uri, XSD.xdouble.uri -> JsonPrimitive(lit.float)
            else -> JsonPrimitive(lit.string)
        }
    }
    // invalid
    else {
        throw InvalidTripleError("Don't know what this is", elementIri, predicate, obj)
    }
}

fun FlexoModelHandler.extractModelElementToJson(elementIri: String): JsonObject {
    // direct outgoing properties of element
    val out = indexOut(elementIri)

    // extract type
    val type = out[RDF.type].resource()?.uri?.autoSuffix
    val id = elementIri.urnSuffix

    // properties whose authoritative (ordered) form is carried by a JSON
    // array annotation; the plain sysml: triples for these are skipped
    val annotatedKeys = out.keys
        .filter { it.uri.startsWith(SYSMLV2.ANNOTATION_JSON) }
        .map { it.uri.urnSuffix }
        .toSet()

    return buildJsonObject {
        put("@type", type)
        put("@id", id)

        // outgoing properties
        out.forEach { (predicate, values) ->
            // extract the suffix name part
            var propertyKey = predicate.uri.autoSuffix

            // reference the first value
            val obj = values.elementAt(0)

            if(predicate.uri.startsWith(SYSMLV2.VOCABULARY)) {
                // the JSON annotation carries this property's array form
                if (annotatedKeys.contains(propertyKey)) return@forEach
                if (values.size > 1) {
                    // multi-valued property without an annotation (e.g. data
                    // loaded as raw RDF rather than through this API): emit a
                    // best-effort array rather than dropping the property.
                    // RDF triples are unordered, so sort for determinism.
                    put(propertyKey, buildJsonArray {
                        values.map { jsonFromRdfNode(elementIri, predicate, it) }
                            .sortedBy { it.toString() }
                            .forEach { add(it) }
                    })
                } else {
                    put(propertyKey, jsonFromRdfNode(elementIri, predicate, obj))
                }
            }
            // annotations
            else if(predicate.uri.startsWith(SYSMLV2.ANNOTATION_JSON)) {
                // expect exactly 1 object
                if(values.size != 1) {
                    throw InvalidTripleError("Expected exactly 1 object with this predicate", elementIri, predicate, obj)
                }

                // object is not a Literal
                if (!obj.isLiteral) {
                    throw InvalidTripleError("Expected annotation property to point to an RDF literal", elementIri, predicate, obj)
                }

                // cast to literal
                val lit = obj.asLiteral()

                // expect valid JSON
                val jsonElement = try {
                    Json.parseToJsonElement(lit.string)
                } catch (parse: Error) {
                    throw InvalidTripleError("Expected annotation property to encode a JSON element", elementIri, predicate, obj)
                }

                // infer property key from URN
                propertyKey = predicate.uri.urnSuffix

                // add parsed element to JSON object
                put(propertyKey, jsonElement)
            }
            // something else
            else {
                //throw InvalidTripleError("Unrecognized triple purpose", elementIri, predicate, obj)
            }
        }
    }
}

fun Route.ElementApi() {
    // get an element
    get<Paths.getElementByProjectCommitId> { getElement ->
        requireValidId(getElement.projectId, "projectId")
        requireValidId(getElement.commitId, "commitId")
        requireValidId(getElement.elementId, "elementId")
        val elementIri = SYSMLV2.element(getElement.elementId).uri

        // submit POST request to query model
        val flexoResponse = flexoRequestPost {
            orgPath("/repos/${getElement.projectId}/locks/Commit.${getElement.commitId}/query")
            sparqlQuery {
                modelElementConstructQuery("<$elementIri>")
            }
        }

        // forward failures to client
        if(flexoResponse.isFailure()) {
            return@get forward(flexoResponse)
        }

        // parse the response model, extract the target element to JSON, and reply to client
        val element = flexoResponse.parseModel {
            // an empty result means no such element at this commit
            if (!model.listStatements(model.getResource(elementIri), null, null as RDFNode?).hasNext()) null
            else extractModelElementToJson(elementIri)
        } ?: return@get call.respond(HttpStatusCode.NotFound)
        call.respond(element)
    }

    // get multiple elements
    get<Paths.getElementsByProjectCommit> { getElements ->
        requireValidId(getElements.projectId, "projectId")
        requireValidId(getElements.commitId, "commitId")
        // submit POST request to query model
        val flexoResponse = flexoRequestGet {
            orgPath("/repos/${getElements.projectId}/locks/Commit.${getElements.commitId}/graph")
        }

        // forward failures to client
        if(flexoResponse.isFailure()) {
            return@get forward(flexoResponse)
        }
        // parse the response model, extract the elements to JSON, and reply to client
        val result = buildJsonArray {
            flexoResponse.parseModel {
                for(subject in model.listSubjects()) {
                    if (subject.isAnon) continue
                    add(extractModelElementToJson(subject.uri))
                }
            }
        }
        call.respond(result)
    }
    //TODO this is wrong
    get<Paths.getProjectUsageByProjectCommitElement> {
        requireValidId(it.projectId, "projectId")
        requireValidId(it.commitId, "commitId")
        requireValidId(it.elementId, "elementId")
        val flexoResponse = flexoRequestPost {
            orgPath("/repos/${it.projectId}/locks/Commit.${it.commitId}/query")
            sparqlQuery {
                """
                prefix sysml: <https://www.omg.org/spec/SysML#>
                construct {
                  ?element a sysml:ProjectUsage ;
                         ?element_p ?element_o .
                }
                where {
                  ?element a sysml:ProjectUsage ;
                        ?element_p ?element_o .
                }
                """.trimIndent()
            }
        }

        // forward failures to client
        if(flexoResponse.isFailure()) {
            return@get forward(flexoResponse)
        }

        // parse the response model, extract the elements to JSON, and reply to client
        val result = buildJsonArray {
            flexoResponse.parseModel {
                for(subject in model.listSubjects()) {
                    if (subject.isAnon) continue
                    add(extractModelElementToJson(subject.uri))
                }
            }
        }
        call.respond(result)
    }

    get<Paths.getRootsByProjectCommit> {
        requireValidId(it.projectId, "projectId")
        requireValidId(it.commitId, "commitId")
        // submit POST request to query model
        val flexoResponse = flexoRequestPost {
            orgPath("/repos/${it.projectId}/locks/Commit.${it.commitId}/query")
            sparqlQuery {
                """
                prefix sysml: <https://www.omg.org/spec/SysML#>
                prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
                construct {
                  ?element a ?element_type ;
                         ?element_p ?element_o .
                }
                where {
                  ?element a ?element_type ;
                        ?element_p ?element_o .
                  
                  optional { ?element sysml:owner ?owner . }
                  optional { ?element sysml:owningRelatedElement ?related . }

                  filter ((!bound(?owner) || ?owner = rdf:nil) && (!bound(?related) || ?related = rdf:nil))
                }
                """.trimIndent()
            }
        }

        // forward failures to client
        if(flexoResponse.isFailure()) {
            return@get forward(flexoResponse)
        }

        // parse the response model, extract the elements to JSON, and reply to client
        val result = buildJsonArray {
            flexoResponse.parseModel {
                for(subject in model.listSubjects()) {
                    if (subject.isAnon) continue
                    add(extractModelElementToJson(subject.uri))
                }
            }
        }
        call.respond(result)
    }

}
