/**
* Systems Modeling API and Services
* REST/HTTP platform specific model (PSM) for the Systems Modeling API and Services
*
* The version of the OpenAPI document: 1.0
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openmbee.flexo.sysmlv2.apis

import io.ktor.http.*
import io.ktor.server.application.*
import io.ktor.server.plugins.*
import io.ktor.server.resources.*
import io.ktor.server.response.*
import io.ktor.server.routing.*

import kotlinx.serialization.json.*
import kotlinx.serialization.encodeToString
import org.apache.jena.arq.querybuilder.ConstructBuilder
import org.apache.jena.arq.querybuilder.UpdateBuilder
import org.apache.jena.graph.Node
import org.apache.jena.rdf.model.Property
import org.apache.jena.rdf.model.RDFNode
import org.apache.jena.sparql.expr.Expr
import org.apache.jena.vocabulary.DCTerms
import org.apache.jena.vocabulary.RDF
import org.openmbee.flexo.sysmlv2.*
import org.openmbee.flexo.sysmlv2.models.CompositeConstraint
import org.openmbee.flexo.sysmlv2.models.Identified
import org.openmbee.flexo.sysmlv2.models.PrimitiveConstraint
import org.openmbee.flexo.sysmlv2.models.Query
import org.openmbee.flexo.sysmlv2.infrastructure.generateId
import org.openmbee.flexo.sysmlv2.infrastructure.requireValidId
import org.openmbee.flexo.sysmlv2.models.QueryRequest

fun PrimitiveConstraint.toSparql(cb: ConstructBuilder): Expr {
    val p: Node
    // property names are client input; only variable-safe characters may
    // appear in the SPARQL variable derived from them
    var pvar: String = property.replace(Regex("[^A-Za-z0-9_]"), "_")
    when(property) {
        "@id" -> { p = SYSMLV2.prop("elementId").asNode(); pvar = "id" }
        "@type" -> { p = RDF.type.asNode(); pvar = "Metatype" }
        else -> { p = SYSMLV2.prop(property).asNode() }
    }
    // schema: value is null, or an array of at least one scalar/Identified/null;
    // a null value (either form) matches elements lacking the property
    val values = value ?: listOf(JsonNull)
    if (values.isEmpty()) {
        throw BadRequestException("PrimitiveConstraint value must not be empty")
    }
    // null stands for "property absent"; everything else becomes a comparable node
    val nodes: List<Node?> = values.map { el ->
        when(el) {
            is JsonObject -> {
                if (el.containsKey("@id")) {
                    SYSMLV2.element(el["@id"]!!.jsonPrimitive.content).asNode()
                } else {
                    throw BadRequestException("PrimitiveConstraint value object must contain @id")
                }
            }
            is JsonPrimitive -> {
                if (el == JsonNull) {
                    null
                } else {
                    if (property == "@type") SYSMLV2.type(el.content).asNode() else el.toRdfLiteralNode()
                }
            }
            else -> throw BadRequestException("Unexpected JSON element type in PrimitiveConstraint value")
        }
    }
    // the pattern must be optional so that (a) null values can match elements
    // lacking the property and (b) an or-composite over different properties
    // does not require all of them to be present; bound() guards below keep
    // required-presence semantics for the individual comparisons
    cb.addOptional("?e", p, "?$pvar")
    val ef = cb.exprFactory
    val matchesAbsent = nodes.any { it == null }
    val comparable = nodes.filterNotNull()
    val expr = when(operator) {
        // per the OMG schema "=" takes an array; both it and "in" are set
        // membership over the array's values
        PrimitiveConstraint.Operator.Equal, PrimitiveConstraint.Operator.In -> {
            val membership = comparable
                .map { ef.eq("?$pvar", it) as Expr }
                .reduceOrNull { acc, e -> ef.or(acc, e) }
                ?.let { ef.and(ef.bound("?$pvar"), it) as Expr }
            val absent = if (matchesAbsent) ef.not(ef.bound("?$pvar")) as Expr else null
            listOfNotNull(absent, membership).reduce { acc, e -> ef.or(acc, e) }
        }
        else -> {
            if (matchesAbsent || comparable.size != 1) {
                throw BadRequestException("PrimitiveConstraint operator '${operator.value}' requires exactly one non-null value")
            }
            val v = comparable[0]
            val cmp = when(operator) {
                PrimitiveConstraint.Operator.Less_Than -> ef.lt("?$pvar", v)
                PrimitiveConstraint.Operator.Less_Than_Equal -> ef.le("?$pvar", v)
                PrimitiveConstraint.Operator.Greater_Than -> ef.gt("?$pvar", v)
                PrimitiveConstraint.Operator.Greater_Than_Equal -> ef.ge("?$pvar", v)
                else -> throw BadRequestException("Unsupported PrimitiveConstraint operator '${operator.value}'")
            }
            ef.and(ef.bound("?$pvar"), cmp)
        }
    }
    return if (inverse) ef.not(expr) else expr
}
fun CompositeConstraint.toSparql(cb: ConstructBuilder): Expr {
    if (constraint.size < 2) throw BadRequestException("CompositeConstraint must have at least 2 constraints")
    val c = mutableListOf<Expr>()
    constraint.forEach {
        if (it is PrimitiveConstraint) {
            c.add(it.toSparql(cb))
        }
        if (it is CompositeConstraint) {
            c.add(it.toSparql(cb))
        }
    }
    val ef = cb.exprFactory
    return c.reduce {acc, b ->
        when(operator) {
            CompositeConstraint.Operator.and -> ef.and(acc, b)
            CompositeConstraint.Operator.or -> ef.or(acc, b)
        }
    }
}

suspend fun RoutingContext.createOrUpdateQuery(
    queryId: String, projectId: String, queryRequest: QueryRequest, post: Boolean): Pair<FlexoResponse, Query> {
    val query = Query(atId = queryId,
        atType = Query.AtType.Query,
        owningProject = Identified(projectId),
        select = queryRequest.select ?: throw BadRequestException("Query must have a select"),
        where = queryRequest.where ?: throw BadRequestException("Query must have a where"))
    val queryString = Json.encodeToString<Query>(query)
    val queryUri = SYSMLV2.query(queryId)
    val insertBuilder = UpdateBuilder().addInsert(queryUri, DCTerms.description, queryString)
    val flexoResponse = flexoRequestPost {
        orgPath("/repos/$projectId/scratches/queries/update")
        // construct body payload
        sparqlUpdate {
            """
                delete { <$queryUri> ?p ?o . } where {  <$queryUri> ?p ?o . };
                ${insertBuilder.buildRequest()}
            """.trimIndent()
        }
    }
    return Pair(flexoResponse, query)
}

suspend fun RoutingContext.runQuery(
    query: QueryRequest, projectId: String, commitId: String?): FlexoResponse {
    var branchId = "master"
    if (commitId == null) {
        // get default branch of project
        val projectResponse = flexoRequestGet {
            orgPath("/repos/$projectId")
        }
        // nonexistent/unauthorized project: let the caller forward the failure
        if (projectResponse.isFailure()) {
            return projectResponse
        }
        projectResponse.parseModel {
            val repos = model.listSubjectsWithProperty(RDF.type, MMS.Repo)
            if (repos.hasNext()) {
                branchId = repos.next().outgoing()[SYSMLV2.DEFAULT_BRANCH_ID]?.literal() ?: "master"
            }
        }
    }
    val cb = ConstructBuilder().addConstruct("?e", "?p", "?o")
        .addWhere("?e", "?p", "?o")
        .addPrefixes(SYSMLV2_PREFIX_MAPPING)
    val filter = when(query.where) {
        is CompositeConstraint -> query.where.toSparql(cb)
        is PrimitiveConstraint -> query.where.toSparql(cb)
        null -> null
    }
    cb.addFilter(filter)
    val queryPath = if (commitId == null) "/repos/$projectId/branches/$branchId/query"
                    else "/repos/$projectId/locks/Commit.$commitId/query"
    return flexoRequestPost {
        orgPath(queryPath)
        sparqlQuery {
            cb.toString()
        }
    }
}

// apply a query's select projection: keep only the requested properties
fun JsonObject.projectTo(select: List<String>?): JsonObject {
    if (select.isNullOrEmpty()) return this
    return JsonObject(filterKeys { it in select })
}

suspend fun RoutingContext.getQuery(projectId: String, queryId: String): Pair<FlexoResponse, Query?> {
    val uri = SYSMLV2.query(queryId).uri
    val flexoResponse = flexoRequestPost {
        orgPath("/repos/$projectId/scratches/queries/query")
        sparqlQuery {
                """
                    construct { 
                        <$uri> ?p ?o .
                    } where {
                        <$uri> ?p ?o .
                    }
                """.trimIndent()
        }
    }
    if (flexoResponse.isFailure()) {
        return Pair(flexoResponse, null)
    }
    // parse the response model, convert it to JSON, and reply to client
    val query = flexoResponse.parseModel {
        model.listSubjects().mapWith { it2 ->
            queryFromResponse(it2.outgoing())
        }.toList().firstOrNull()
    }
    return Pair(flexoResponse, query)
}

fun queryFromResponse(
    outgoing: Map<Property, Set<RDFNode>>,
): Query {
    val query = outgoing[DCTerms.description]?.literal()?: ""
    return Json.decodeFromString<Query>(query)
}

fun Route.QueryApi() {

    delete<Paths.deleteQueryByProjectAndId> {
        val projectId = it.projectId
        val queryId = it.queryId
        requireValidId(projectId, "projectId")
        requireValidId(queryId, "queryId")
        val query = getQuery(projectId, queryId)
        if (query.first.isFailure()) {
            return@delete forward(query.first)
        }
        val uri = SYSMLV2.query(queryId).uri
        val flexoResponse = flexoRequestPost {
            orgPath("/repos/$projectId/scratches/queries/update")
            sparqlUpdate {
                """
                    delete { 
                        <$uri> ?p ?o .
                    } where {
                        <$uri> ?p ?o .
                    }
                """.trimIndent()
            }
        }
        if(flexoResponse.isFailure()) {
            return@delete forward(flexoResponse)
        }
        call.respond<Query>(query.second ?: return@delete call.respond(HttpStatusCode.NotFound))
    }

    get<Paths.getQueriesByProject> {
        val projectId = it.projectId
        requireValidId(projectId, "projectId")
        val flexoResponse = flexoRequestGet {
            orgPath("/repos/$projectId/scratches/queries/graph")
        }
        if(flexoResponse.isFailure()) {
            return@get forward(flexoResponse)
        }
        // parse the response model, convert it to JSON, and reply to client
        val queries = flexoResponse.parseModel {
            model.listSubjects().mapWith { it2 ->
                queryFromResponse(it2.outgoing())
            }.toList()
        }
        respondPage(queries, it.pageSize, it.pageAfter) { query -> query.atId }
    }

    get<Paths.getQueryByProjectAndId> {
        val projectId = it.projectId
        val queryId = it.queryId
        requireValidId(projectId, "projectId")
        requireValidId(queryId, "queryId")
        val res = getQuery(projectId, queryId)
        if (res.first.isFailure()) {
            return@get forward(res.first)
        }
        // parse the response model, convert it to JSON, and reply to client
        call.respond<Query>(res.second ?: return@get call.respond(HttpStatusCode.NotFound))
    }

    get<Paths.getQueryResultsByProjectIdQuery> {
        throw NotImplementedError()
    }

    get<Paths.getQueryResultsByProjectIdQueryId> {
        val projectId = it.projectId
        val queryId = it.queryId
        val commitId = it.commitId
        requireValidId(projectId, "projectId")
        requireValidId(queryId, "queryId")
        commitId?.let { id -> requireValidId(id, "commitId") }
        // get query
        val res = getQuery(projectId, queryId)
        if (res.first.isFailure()) {
            return@get forward(res.first)
        }
        val query = res.second ?: return@get call.respond(HttpStatusCode.NotFound)
        val flexoResponse = runQuery(QueryRequest(where = query.where), projectId, commitId)
        // forward failures to client
        if (flexoResponse.isFailure()) {
            return@get forward(flexoResponse)
        }

        // parse the response model, extract the elements to JSON, and reply to client
        call.respond(buildJsonArray {
            flexoResponse.parseModel {
                for(subject in model.listSubjects()) {
                    if (subject.isAnon) continue
                    add(extractModelElementToJson(subject.uri).projectTo(query.select))
                }
            }
        })
    }

    post<QueryRequest>("/projects/{projectId}/query-results") {
        val projectId = call.parameters["projectId"]!!
        val commitId = call.parameters["commitId"]
        requireValidId(projectId, "projectId")
        commitId?.let { id -> requireValidId(id, "commitId") }
        val flexoResponse = runQuery(it, projectId, commitId)
        // forward failures to client
        if (flexoResponse.isFailure()) {
            return@post forward(flexoResponse)
        }
        // parse the response model, extract the elements to JSON, and reply to client
        call.respond(buildJsonArray {
            flexoResponse.parseModel {
                for(subject in model.listSubjects()) {
                    if (subject.isAnon) continue
                    add(extractModelElementToJson(subject.uri).projectTo(it.select))
                }
            }
        })
    }

    post<QueryRequest>("/projects/{projectId}/queries") {
        val projectId = call.parameters["projectId"]!!
        requireValidId(projectId, "projectId")
        it.atId?.let { id -> requireValidId(id, "@id") }
        // use provided query ID or generate one if not provided
        val queryId = it.atId ?: generateId()
        val response = createOrUpdateQuery(queryId, projectId, it, true)
        if (response.first.isFailure()) {
            return@post forward(response.first)
        }
        call.respond(response.second)
    }

    put<QueryRequest>("/projects/{projectId}/queries/{queryId}") {
        val projectId = call.parameters["projectId"]!!
        val queryId = call.parameters["queryId"]!!
        requireValidId(projectId, "projectId")
        requireValidId(queryId, "queryId")
        val response = createOrUpdateQuery(queryId, projectId, it, false)
        if (response.first.isFailure()) {
            return@put forward(response.first)
        }
        call.respond(response.second)
    }
}
