/**
* Systems Modeling API and Services
* REST/HTTP platform specific model (PSM) for the Systems Modeling API and Services
*
* The version of the OpenAPI document: 1.0
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openmbee.flexo.sysmlv2.apis

import io.ktor.http.*
import io.ktor.server.application.*
import io.ktor.server.auth.*
import io.ktor.server.response.*
import org.openmbee.flexo.sysmlv2.Paths
import io.ktor.server.resources.options
import io.ktor.server.resources.get
import io.ktor.server.resources.post
import io.ktor.server.resources.put
import io.ktor.server.resources.delete
import io.ktor.server.resources.head
import io.ktor.server.resources.patch
import io.ktor.server.routing.*
import kotlinx.serialization.json.Json
import kotlinx.serialization.decodeFromString
import kotlinx.serialization.json.JsonObject
import org.openmbee.flexo.sysmlv2.models.Query
import org.openmbee.flexo.sysmlv2.models.QueryRequest

fun Route.QueryApi() {

    delete<Paths.deleteQueryByProjectAndId> {

        call.respond("")
    }

    get<Paths.getQueriesByProject> {

        call.respond("")
    }

    get<Paths.getQueryByProjectAndId> {

        call.respond("")
    }

    get<Paths.getQueryResultsByProjectIdQuery> {

        call.respond("")
    }

    get<Paths.getQueryResultsByProjectIdQueryId> {

        call.respond("")
    }

    post<QueryRequest>("/projects/{projectId}/query-results") {
        print(it.atType)
        call.respond(it)
    }

    post<QueryRequest>("/projects/{projectId}/queries") {
        call.respond(it)
    }

    put<QueryRequest>("/projects/{projectId}/queries/{queryId}") {
        call.respond(it)
    }
}
