sonar.projectKey=Open-MBEE_flexo-mms-sysmlv2
sonar.organization=openmbee
sonar.language=kotlin
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
sonar.sources=src/main/
sonar.tests=src/test/
