package org.openmbee.flexo.sysmlv2.util

import io.ktor.client.request.*
import io.ktor.client.statement.*
import io.ktor.http.*
import io.ktor.server.testing.*

/**
 * Send an HTTP request through the in-process test client, automatically
 * attaching the `Authorization: Bearer <jwt>` header generated by
 * [authorization].
 */
suspend fun ApplicationTestBuilder.httpRequest(
    method: HttpMethod,
    uri: String,
    auth: AuthStruct = superAdminAuth,
    setup: HttpRequestBuilder.() -> Unit = {}
): HttpResponse {
    return client.request {
        this.method = method
        this.url(uri)
        header(HttpHeaders.Authorization, authorization(auth))
        setup()
    }
}

suspend fun ApplicationTestBuilder.httpGet(
    uri: String,
    auth: AuthStruct = superAdminAuth,
    setup: HttpRequestBuilder.() -> Unit = {}
): HttpResponse = httpRequest(HttpMethod.Get, uri, auth, setup)

suspend fun ApplicationTestBuilder.httpPost(
    uri: String,
    auth: AuthStruct = superAdminAuth,
    setup: HttpRequestBuilder.() -> Unit = {}
): HttpResponse = httpRequest(HttpMethod.Post, uri, auth, setup)

suspend fun ApplicationTestBuilder.httpPut(
    uri: String,
    auth: AuthStruct = superAdminAuth,
    setup: HttpRequestBuilder.() -> Unit = {}
): HttpResponse = httpRequest(HttpMethod.Put, uri, auth, setup)

suspend fun ApplicationTestBuilder.httpDelete(
    uri: String,
    auth: AuthStruct = superAdminAuth,
    setup: HttpRequestBuilder.() -> Unit = {}
): HttpResponse = httpRequest(HttpMethod.Delete, uri, auth, setup)

suspend fun ApplicationTestBuilder.httpPatch(
    uri: String,
    auth: AuthStruct = superAdminAuth,
    setup: HttpRequestBuilder.() -> Unit = {}
): HttpResponse = httpRequest(HttpMethod.Patch, uri, auth, setup)

suspend fun ApplicationTestBuilder.httpHead(
    uri: String,
    auth: AuthStruct = superAdminAuth,
    setup: HttpRequestBuilder.() -> Unit = {}
): HttpResponse = httpRequest(HttpMethod.Head, uri, auth, setup)

fun HttpRequestBuilder.setJsonBody(body: String) {
    contentType(ContentType.Application.Json)
    setBody(body)
}

fun HttpRequestBuilder.setTurtleBody(body: String) {
    header(HttpHeaders.ContentType, "text/turtle")
    setBody(body)
}
