/**
* Systems Modeling API and Services
* REST/HTTP platform specific model (PSM) for the Systems Modeling API and Services
*
* The version of the OpenAPI document: 1.0
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
@file:UseSerializers(UUIDSerializer::class)

package org.openmbee.flexo.sysmlv2.models

import org.openmbee.flexo.sysmlv2.infrastructure.UUIDSerializer
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.UseSerializers

/**
 *
 * @param head
 * @param name
 * @param atType
 */
@Serializable
data class BranchRequest(
    val head: Identified,
    val name: kotlin.String,
    @SerialName("@type")
    val atType: BranchRequest.AtType? = null
)
{
    /**
    *
    * Values: Branch
    */
    enum class AtType(val value: kotlin.String){
        Branch("Branch");
    }
}

