/**
* Systems Modeling API and Services
* REST/HTTP platform specific model (PSM) for the Systems Modeling API and Services
*
* The version of the OpenAPI document: 1.0
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
@file:UseSerializers(UUIDSerializer::class)

package org.openmbee.flexo.sysmlv2.models

import org.openmbee.flexo.sysmlv2.infrastructure.UUIDSerializer
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.UseSerializers

import org.openmbee.flexo.sysmlv2.models.Constraint

/**
 *
 * @param atType
 * @param constraint
 * @param `operator`
 */
@Serializable
data class CompositeConstraintRequest(
    @SerialName("@type")
    val atType: CompositeConstraintRequest.AtType,
    val constraint: kotlin.collections.List<Constraint>,
    val `operator`: CompositeConstraintRequest.`Operator`
)
{
    /**
    *
    * Values: CompositeConstraint
    */
    enum class AtType(val value: kotlin.String){
        CompositeConstraint("CompositeConstraint");
    }
    /**
    *
    * Values: and,or
    */
    enum class `Operator`(val value: kotlin.String){
        and("and"),
        or("or");
    }
}

