/**
* Systems Modeling API and Services
* REST/HTTP platform specific model (PSM) for the Systems Modeling API and Services
*
* The version of the OpenAPI document: 1.0
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openmbee.flexo.sysmlv2.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 *
 * @param atId
 * @param atType
 */
@Serializable
data class DataIdentity(
    @SerialName("@id")
    val atId: String,
    @SerialName("@type")
    val atType: DataIdentity.AtType
)
{
    /**
    *
    * Values: DataIdentity
    */
    enum class AtType(val value: kotlin.String){
        DataIdentity("DataIdentity");
    }
}
