/**
* Systems Modeling API and Services
* REST/HTTP platform specific model (PSM) for the Systems Modeling API and Services
*
* The version of the OpenAPI document: 1.0
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
@file:UseSerializers(UUIDSerializer::class)

package org.openmbee.flexo.sysmlv2.models

import org.openmbee.flexo.sysmlv2.infrastructure.UUIDSerializer
import com.google.gson.annotations.SerializedName
import kotlinx.serialization.Serializable
import kotlinx.serialization.UseSerializers

import org.openmbee.flexo.sysmlv2.models.ElementFilterMembership
import org.openmbee.flexo.sysmlv2.models.FeatureMembership
import org.openmbee.flexo.sysmlv2.models.FeatureValue
import org.openmbee.flexo.sysmlv2.models.Identified
import org.openmbee.flexo.sysmlv2.models.OwningMembershipAnyOf
import org.openmbee.flexo.sysmlv2.models.TransitionFeatureKind
import org.openmbee.flexo.sysmlv2.models.VariantMembership
import org.openmbee.flexo.sysmlv2.models.VisibilityKind

/**
 *
 * @param atId
 * @param atType
 * @param aliasIds
 * @param declaredName
 * @param declaredShortName
 * @param documentation
 * @param elementId
 * @param isImplied
 * @param isImpliedIncluded
 * @param isLibraryElement
 * @param memberElement
 * @param memberElementId
 * @param memberName
 * @param memberShortName
 * @param membershipOwningNamespace
 * @param name
 * @param ownedAnnotation
 * @param ownedElement
 * @param ownedMemberElement
 * @param ownedMemberElementId
 * @param ownedMemberName
 * @param ownedMemberShortName
 * @param ownedRelatedElement
 * @param ownedRelationship
 * @param owner
 * @param owningMembership
 * @param owningNamespace
 * @param owningRelatedElement
 * @param owningRelationship
 * @param qualifiedName
 * @param relatedElement
 * @param shortName
 * @param source
 * @param target
 * @param textualRepresentation
 * @param visibility
 * @param feature
 * @param ownedMemberFeature
 * @param owningType
 * @param type
 * @param ownedMemberParameter
 * @param ownedSubjectParameter
 * @param ownedStakeholderParameter
 * @param ownedActorParameter
 * @param ownedResultExpression
 * @param kind
 * @param ownedConstraint
 * @param referencedConstraint
 * @param ownedConcern
 * @param referencedConcern
 * @param ownedRequirement
 * @param verifiedRequirement
 * @param ownedObjectiveRequirement
 * @param action
 * @param transitionFeature
 * @param ownedRendering
 * @param referencedRendering
 * @param condition
 * @param featureWithValue
 * @param isDefault
 * @param isInitial
 * @param `value`
 * @param ownedVariantUsage
 */
@Serializable
data class OwningMembership(
    @SerializedName("@id")
    val atId: java.util.UUID,
    @SerializedName("@type")
    val atType: OwningMembership.AtType,
    val aliasIds: kotlin.collections.List<kotlin.String>,
    val declaredName: kotlin.String,
    val declaredShortName: kotlin.String,
    val documentation: kotlin.collections.List<Identified>,
    val elementId: kotlin.String,
    val isImplied: kotlin.Boolean,
    val isImpliedIncluded: kotlin.Boolean,
    val isLibraryElement: kotlin.Boolean,
    val memberElement: Identified,
    val memberElementId: kotlin.String,
    val memberName: kotlin.String,
    val memberShortName: kotlin.String,
    val membershipOwningNamespace: Identified,
    val name: kotlin.String,
    val ownedAnnotation: kotlin.collections.List<Identified>,
    val ownedElement: kotlin.collections.List<Identified>,
    val ownedMemberElement: Identified,
    val ownedMemberElementId: kotlin.String,
    val ownedMemberName: kotlin.String,
    val ownedMemberShortName: kotlin.String,
    val ownedRelatedElement: kotlin.collections.List<Identified>,
    val ownedRelationship: kotlin.collections.List<Identified>,
    val owner: Identified,
    val owningMembership: Identified,
    val owningNamespace: Identified,
    val owningRelatedElement: Identified,
    val owningRelationship: Identified,
    val qualifiedName: kotlin.String,
    val relatedElement: kotlin.collections.List<Identified>,
    val shortName: kotlin.String,
    val source: kotlin.collections.List<Identified>,
    val target: kotlin.collections.List<Identified>,
    val textualRepresentation: kotlin.collections.List<Identified>,
    val visibility: VisibilityKind,
    val feature: Identified,
    val ownedMemberFeature: Identified,
    val owningType: Identified,
    val type: Identified,
    val ownedMemberParameter: Identified,
    val ownedSubjectParameter: Identified,
    val ownedStakeholderParameter: Identified,
    val ownedActorParameter: Identified,
    val ownedResultExpression: Identified,
    val kind: TransitionFeatureKind,
    val ownedConstraint: Identified,
    val referencedConstraint: Identified,
    val ownedConcern: Identified,
    val referencedConcern: Identified,
    val ownedRequirement: Identified,
    val verifiedRequirement: Identified,
    val ownedObjectiveRequirement: Identified,
    val action: Identified,
    val transitionFeature: Identified,
    val ownedRendering: Identified,
    val referencedRendering: Identified,
    val condition: Identified,
    val featureWithValue: Identified,
    val isDefault: kotlin.Boolean,
    val isInitial: kotlin.Boolean,
    val `value`: Identified,
    val ownedVariantUsage: Identified
)
{
    /**
    *
    * Values: VariantMembership
    */
    enum class AtType(val value: kotlin.String){
        VariantMembership("VariantMembership");
    }
}

