/**
* Systems Modeling API and Services
* REST/HTTP platform specific model (PSM) for the Systems Modeling API and Services
*
* The version of the OpenAPI document: 1.0
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
@file:UseSerializers(UUIDSerializer::class)

package org.openmbee.flexo.sysmlv2.models

import org.openmbee.flexo.sysmlv2.infrastructure.UUIDSerializer
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.UseSerializers

import org.openmbee.flexo.sysmlv2.models.ConstraintRequest

/**
 *
 * @param atType
 * @param select
 * @param `where`
 */
@Serializable
data class QueryRequest(
    @SerialName("@type")
    val atType: QueryRequest.AtType? = null,
    val select: kotlin.collections.List<kotlin.String>? = null,
    val `where`: ConstraintRequest? = null
)
{
    /**
    *
    * Values: Query
    */
    enum class AtType(val value: kotlin.String){
        Query("Query");
    }
}

