/**
* Systems Modeling API and Services
* REST/HTTP platform specific model (PSM) for the Systems Modeling API and Services
*
* The version of the OpenAPI document: 1.0
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
@file:UseSerializers(UUIDSerializer::class, OffsetDateTimeSerializer::class)

package org.openmbee.flexo.sysmlv2.models

import org.openmbee.flexo.sysmlv2.infrastructure.UUIDSerializer
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.UseSerializers
import org.openmbee.flexo.sysmlv2.infrastructure.OffsetDateTimeSerializer

import org.openmbee.flexo.sysmlv2.models.Identified

/**
 *
 * @param atId
 * @param atType
 * @param created
 * @param name
 * @param owningProject
 * @param referencedCommit
 * @param taggedCommit
 */
@Serializable
data class Tag(
    @SerialName("@id")
    val atId: java.util.UUID,
    @SerialName("@type")
    val atType: Tag.AtType,
    val created: java.time.OffsetDateTime,
    val name: kotlin.String,
    val owningProject: Identified,
    val referencedCommit: Identified,
    val taggedCommit: Identified
)
{
    /**
    *
    * Values: Tag
    */
    enum class AtType(val value: kotlin.String){
        Tag("Tag");
    }
}

