/**
* Systems Modeling API and Services
* REST/HTTP platform specific model (PSM) for the Systems Modeling API and Services
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server.models

import org.openapitools.server.models.Identified

/**
 * 
 * @param atType 
 * @param atId 
 * @param elementEnd 
 * @param externalDataEnd 
 * @param language 
 * @param specification 
 */
data class ExternalRelationshipRequest(
    val atType: ExternalRelationshipRequest.AtType,
    val atId: java.util.UUID? = null,
    val elementEnd: Identified? = null,
    val externalDataEnd: Identified? = null,
    val language: kotlin.String? = null,
    val specification: kotlin.String? = null
) 
{
    /**
    * 
    * Values: ExternalRelationship
    */
    enum class AtType(val value: kotlin.String){
        ExternalRelationship("ExternalRelationship");
    }
}

