/**
* Systems Modeling API and Services
* REST/HTTP platform specific model (PSM) for the Systems Modeling API and Services
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server.models

import org.openapitools.server.models.Identified

/**
 * 
 * @param atType 
 * @param atId 
 * @param usedCommit 
 * @param usedProject 
 */
data class ProjectUsageRequest(
    val atType: ProjectUsageRequest.AtType,
    val atId: java.util.UUID? = null,
    val usedCommit: Identified? = null,
    val usedProject: Identified? = null
) 
{
    /**
    * 
    * Values: ProjectUsage
    */
    enum class AtType(val value: kotlin.String){
        ProjectUsage("ProjectUsage");
    }
}

