/**
* Systems Modeling API and Services
* REST/HTTP platform specific model (PSM) for the Systems Modeling API and Services
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server.models

import org.openapitools.server.models.Constraint
import org.openapitools.server.models.Identified

/**
 * 
 * @param atId 
 * @param atType 
 * @param owningProject 
 * @param select 
 * @param `where` 
 */
data class Query(
    val atId: java.util.UUID,
    val atType: Query.AtType,
    val owningProject: Identified,
    val select: kotlin.collections.List<kotlin.String>,
    val `where`: Constraint
) 
{
    /**
    * 
    * Values: Query
    */
    enum class AtType(val value: kotlin.String){
        Query("Query");
    }
}

